@startuml
'https://plantuml.com/sequence-diagram

autonumber

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
Alice -> Coo: testhahha

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
Coo --> Bob: abcdddd
@enduml